### ISSUE TITLE
sqlalchemy-stubs are installed in conda environment and entered in mypy.ini, but in pre-commit, one gets error: Error importing plugin "sqlmypy": No module named 'sqlmypy'

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [dropbox/sqlalchemy-stubs#243]
I have installed sqlaclhemy-stubs in my local environment (I have tried both versions from pypi and the development version from the github), but when I tried to run mypy analysis via pre-commit, I'm getting the following error message from the mypy:

mypy.ini:6:1: error: Error importing plugin "sqlmypy": No module named 'sqlmypy'

python version is 3.8
mypy version is 0.961
sqlalchemy-stubs version is 0.4

**Comment by sohnya** [comment]
@serhiy-yevtushenko this is my pre-commit config that did the trick: 
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.961'
    hooks:
    -   id: mypy
        additional_dependencies:
          - pydantic
          - sqlalchemy-stubs
```
